#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
# 
# https://github.com/louis-tru/ftr.git
# Description: Build Ftr in macOS 10.15 using GitHub Actions
#


name: Build Ftr

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/louis-tru/ftr.git
  REPO_BRANCH: master
  
jobs:
   build:
    runs-on: macos-10.15

    steps:
    - name: Initialization environment
      run: |
        node -v
        npm i typescript@3.9.7 -g
        java -version
        brew search android-sdk
        brew install android-sdk
        export ANDROID_SDK="/usr/local/share/android-sdk"
        export ANDROID_NDK="/usr/local/share/android-ndk"
        echo $JAVA_HOME
        echo $ANDROID_SDK
        echo $ANDROID_NDK
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
    
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    - name: Clone source code
      working-directory: /workdir
      run: |
        git clone $REPO_URL
    - name: Init git submodule
      run: cd ftr && make init
    - name: Compile Ftr
      id: compile
      run: |
        cd ftr && make install
    
